### ISSUE TITLE
Wiki: wrong/contradictory statement about code execution from EEPROM

### ISSUE THREAD

**Issue by alfredluca** [TG9541/stm8ef#135]
In the Wiki there is are [two statements about code execution from the EEPROM](https://github.com/TG9541/stm8ef/wiki/STM8S-Programming#code-execution-from-different-memory-areas):
1. it doesn't work (with demonstration)
2. it works (without demonstration)

I guess that there was a wrong statement, which was only partially corrected!

**Comment by TG9541** [comment]
Fixed. Code execution from RAM is a feature that's not implemented in EEPROM, and I don't know why I ever claimed that it would work.

**Comment by TG9541** [comment]
There were also wrong log entries on HackaDay, which I edited.

**Comment by TG9541** [comment]
#178 introduces a way to still use the EEPROM for Forth: put ALIAS dictionary entries in it, and save Flash memory for the executable part.
