### ISSUE TITLE
STM8L-Discovery 

### ISSUE THREAD

**Issue by 4yerba** [TG9541/stm8ef#218]
Just a very minor find:
Here .../TG9541/stm8ef/releases under the "STM8L-Discovery" there is a link to the LCD-DISCOVERY/README.md. which links to  the stm8ef/XY-PWM/README.md. Not an issue at all. I'm very impressed with the overall quality of your project.

**Comment by TG9541** [comment]
Hi 4yerba, it's nice seeing you again! 

Thanks for the hint - I fixed the copy&paste snafu :-)
