### ISSUE TITLE
STC1000 Temperature controller... sharing ...

### ISSUE THREAD

**Issue by RandoSY** [TG9541/stm8ef#224]
I found this online ...
https://github.com/Emile666/stc1000_stm8
I  guess there's a flavor of this popular temperature controller that runs a STM8. Does this look like a good candidate for eForth?

![htb1wxpjb4utbunkhfnrq6a9qpxac](https://user-images.githubusercontent.com/609947/45172160-835da100-b1d2-11e8-99b9-89c5f32c8297.jpg)

**Comment by TG9541** [comment]
If it runs on STM8S it can run eForth :-) Sometimes connecting a serial console can be a bit of a trouble (e.g. W1209WK)

The backplane sensor input at the backplane looks really strange:

![backplane](https://raw.githubusercontent.com/Emile666/stc1000_stm8/master/img/schematics_backplane.png)

The the display reuses even sensor and key inputs. Smart move, but it will be difficult to make a serial interface work:

![display and uC](https://raw.githubusercontent.com/Emile666/stc1000_stm8/master/img/schematics_frontpanel.png)

The schematics is from 2016. I wouldn't rule out that a STC-1000 you buy now has a Nuvoton µC.

**Comment by RandoSY** [comment]
I'm going to try this for sure!

**Comment by TG9541** [comment]
If you buy one, please let me know the vendor

**Comment by TG9541** [comment]
I'm closing this for now - please re-open after it's confirmed that the STC1000 (or similar devices) are based on a STM8 controller :-)

**Comment by RandoSY** [comment]
I finally had to reorder this part, and it came in weeks and weeks later :(. However I was delighted to see all the awesome improvements you made to just about every thing. I'm wondering if I can get docker working on an Oracle Virtual Box Ubuntu guest session.... Anyway a lot to get caught up on...

Let me see if I can determine the chip in my new unit.

Cheers!

**Comment by TG9541** [comment]
Thanks for the feedback!  

In a VirtualBox session with a fairly recent Ubuntu (e.g. 18.04 or 16.04) it's possible to install SDCC right away. Also e4thcom should work.

I'm curious which chip they used.

**Comment by RandoSY** [comment]
I had a go at disassembly of my new STC1000, and found a ton of good resources on the web on just how to do so. Unfortunately, the "Black Label" STC1000, although it seems to have remarkably good build quality for its use as intended, seems to have squirreled the micro-controller under neath the LED display?

There might be a small series of solder pads for a pogo pads on the back for programming purposes? Sheer conjecture...

I think my first order of business is to _attempt_ to buy another temperature controller that has the white label, code "0602 05 RQC" Of course there just no telling what will actually be sent. Anyway this is a ton of fun, sleuthing around and seeing what's what.

![1_6e74b463-671d-4b92-a72e-dab4d745872d_1024x1024](https://user-images.githubusercontent.com/609947/60756043-74987400-9fc6-11e9-9e76-59c7d0223b87.jpg)

![2019-07-06 08_14_27-STC-1000-sample-schematic-on-top hilite](https://user-images.githubusercontent.com/609947/60756044-7e21dc00-9fc6-11e9-9a05-59ac8235c03a.png)

**Comment by RandoSY** [comment]
There are four "flavors" of STC1000 I am chasing down...

1. Silver Label (covers joint)

2. White Label (covers joint)

3. White Label (0602 05 RCQ)

4. Black Label (does not cover joint)

**Comment by TG9541** [comment]
It's almost like one has to be prepared to replace the display board entirely.

**Comment by RandoSY** [comment]
Just an quick update on this, unfortunately I found this to be true... not surprisingly 

1. There is no correspondence between the label color and what you find inside... or/and

2. Perhaps more correctly, what is pictured for sale may or may not be what you get

That doesn't preclude the merit of seeing how the technology has evolved over time to be more efficient, and easier to manufacture, which is in itself quite enlightening I think.

**Comment by TG9541** [comment]
Thanks for the update! 
Maybe the box is sufficiently standardized that it's possible to replace the display PCB?
