### ISSUE TITLE
XY-PWM  inputs?

### ISSUE THREAD

**Issue by RandoSY** [TG9541/stm8ef#231]
Would you happen to know if one of the PWM outputs of the XY-PWM  could be coaxed into being an Analog input for A/D conversion. I've been looking for a schematic with no success. 

Thanks!

![image](https://user-images.githubusercontent.com/609947/45824520-31327a80-bcbe-11e8-9105-3f8094d24a99.png)

![pwm-generator-circuit](https://user-images.githubusercontent.com/609947/45825288-e6196700-bcbf-11e8-8c70-9af4d270ed68.jpg)

**Comment by TG9541** [comment]
@plumbum traced the GPIO connections here https://github.com/TG9541/stm8ef/tree/master/XY-PWM 
Pwm1 is controlled by PD3 which is an Ain. A modification of the be board should be easy.
