### ISSUE TITLE
Docs for STM8 eForth Compiler and Assembly

### ISSUE THREAD

**Issue by TG9541** [TG9541/stm8ef#234]
I started a [Compiler and Assembly](https://github.com/TG9541/stm8ef/wiki/STM8-eForth-Compiler-and-Assembly) Wiki page that needs review. 

Help would be highly appreciated :-)

**Comment by sbridger** [comment]
This is not exactly on topic, but related: 

While looking at [ebike displays](https://github.com/OpenSource-EBike-firmware/TSDZ2-Smart-EBike/tree/master/src/display/KT-LCD3),  I wonder about the process to add/mix/graft e4th into a primarily C project.

**Comment by TG9541** [comment]
This should be sufficient.

@VK6TT thanks for the text!
