### ISSUE TITLE
Z for 7-seg LED is wrong way around

### ISSUE THREAD

**Issue by RigTig** [TG9541/stm8ef#25]
Very minor issue, but when you've only got 7 segments S and Z should still be different. I changed last byte of list at PAT7SAZ: in forth.asm from 0x6D (like S) to 0x5B (like 2).

**Comment by TG9541** [comment]
Hi RigTig, thanks for reporting!

I guess that this kind of stupid errors is proof enough that I didn't pinch this 7-single-bits-yes-please-count-them extreme minimalistic binary art somewhere else ;-)
