### ISSUE TITLE
Standalone device

### ISSUE THREAD

**Issue by Rahul24-06** [TG9541/stm8ef#315]
Is there any reference schematic for a standalone STM8S001J3 microcontroller?

**Comment by TG9541** [comment]
The schematics from [AN2752](https://www.st.com/resource/en/application_note/cd00194637-getting-started-with-stm8s-and-stm8af-microcontrollers--stmicroelectronics.pdf) below is the closest thing to a reference schematic for the STM8S001J3 that I'm aware of: 
![image](https://user-images.githubusercontent.com/5466977/83336655-7392c400-a2b5-11ea-9d8d-e8ec917a5d49.png)
Of course, this chip doesn't need other supplies than VSS, VDD and VCAP, so most likely the following applies: 
![image](https://user-images.githubusercontent.com/5466977/83336670-860cfd80-a2b5-11ea-9419-f2424089b117.png)
The chip is rather robust - the reference design from ST doesn't take the layout recommendations too literally:
![image](https://user-images.githubusercontent.com/5466977/31315055-d1cd1eac-ac0f-11e7-89d4-184a421e783f.jpg)
Some more information is [here in the Wiki](https://github.com/TG9541/stm8ef/wiki/Breakout-Boards#homemade-stm8s001j3m3-breakout-board).

**Comment by Rahul24-06** [comment]
That's interesting. When it comes to programming this controller, how is the connection made with ST-Link / JTAG?

**Comment by TG9541** [comment]
It's actually very simple: make sure that [all of the GPIOs internally bonded to pin 8](https://github.com/TG9541/stm8ef/wiki/STM8-Low-Density-Devices#stm8s001j3) are in input state at least some time (and not permanently driven by an external circuit). This means a half-duplex serial connection for a console, that's normally in RX mode, fits the bill. 

The [stm8s001rs485](https://github.com/TG9541/stm8s001rs485) is an example:
![i](https://raw.githubusercontent.com/TG9541/stm8s001rs485/master/doc/STM8S001J3_RS485_sch.png)

Here, PD1/SWIM is J2.2, the same as RX/TX of the half-duplex RS485 interface.

**Comment by Rahul24-06** [comment]
Thanks for sharing.
