### ISSUE TITLE
Bad Merge

### ISSUE THREAD

**Issue by hexagon5un** [TG9541/stm8ef#33]
Thomas, I made a merge into this repo instead of my fork, and directly into master.  I'm sorry about that.  

It was minor stuff in the XH branch, but b/c I had just merged some of RigTig's work, it made it look like part of my merge.  

If you want to undo it, feel free.  I'll submit a pull from my fork instead, which I probably should have done in the first place.

**Comment by TG9541** [comment]
No problem - at least one can't say that our network graph looks boring ;-) As far as I can tell all is OK. 

In the future we should try to do some review, though. Continuous integration is also on my list.
We can all use this repository with feature branches + integration branch (develop) + release branch (master). Working with feature branches in a fork is almost the same.
