### ISSUE TITLE
Nucleo-8s207k8 supported?

### ISSUE THREAD

**Issue by RandoSY** [TG9541/stm8ef#381]
![image PF268413 en feature-description-include-personalized-no-cpn-medium](https://user-images.githubusercontent.com/609947/99884774-b5664c80-2bfe-11eb-8fa9-93eb1f3e6669.jpg)

Nucleo-8s207k8

Did you recently post that you've added support for this Arduino Nano footprint compatible Nucleo?

**Comment by TG9541** [comment]
I haven't tried with a real STM8S207K8T6C chip but the [STM8S207RB](https://github.com/TG9541/stm8ef/tree/master/STM8S207RB) configuration and the binary in the release archive should work right away.

The serial interface should be pin30-TX and pin31-RX.

**Comment by RandoSY** [comment]
Thanks, I keep you posted on progress...

**Comment by TG9541** [comment]
@RandoSY: In the [Nucleo-8S207K8 User Manual](https://www.st.com/resource/en/user_manual/dm00489875-stm8-nucleo32-board-mb1442-stmicroelectronics.pdf) I found the following about the COM port:

![image](https://user-images.githubusercontent.com/5466977/99909960-bc1ebd80-2ceb-11eb-9671-e104ca51b750.png)

It would be interesting to know if the virtual COM port works (under Linux or Windows).
