### ISSUE TITLE
More photos for the Wiki

### ISSUE THREAD

**Issue by TG9541** [TG9541/stm8ef#40]
Unlike GitHub Issues the GitHub Wiki doesn't have an image upload feature. 
This issue provides storage for the Wiki.

**Comment by TG9541** [comment]
http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

![stm8s003f3_breakout](https://user-images.githubusercontent.com/5466977/28246358-8b02e86e-6a18-11e7-9375-c586723007c0.jpg)

**Comment by TG9541** [comment]
W1209 full duplex serial interface using test hook clips
![w1209_connect](https://user-images.githubusercontent.com/5466977/28498707-d8dd34aa-6fa3-11e7-9b5f-d84e8fded1bb.png)

W1209 board with attached serial interface cable
![w1209_serial1](https://user-images.githubusercontent.com/5466977/28498708-e2432cac-6fa3-11e7-878b-f7dbc6060866.png)

**Comment by TG9541** [comment]
![stm8s003f3](https://user-images.githubusercontent.com/5466977/28499339-9d925c12-6fb3-11e7-9eae-8b008cb069ee.png)

**Comment by TG9541** [comment]
![w1209](https://user-images.githubusercontent.com/5466977/33417013-d2b29dec-d59f-11e7-8187-e608e856fe16.png)

**Comment by TG9541** [comment]
![sp3485pins](https://user-images.githubusercontent.com/5466977/34650026-2ac4e962-f3ba-11e7-8fe9-5bbcc7faa701.png)

**Comment by VK6TT** [comment]
Some boards pics






![w1209](https://user-images.githubusercontent.com/20902507/36072393-098ebdb6-0f5a-11e8-947c-2984f65668dd.png)
![variant1 rear](https://user-images.githubusercontent.com/20902507/36072538-1cd07d7c-0f5c-11e8-9d43-aeacad1edbab.jpg)
![original rear](https://user-images.githubusercontent.com/20902507/36072539-1d1e9282-0f5c-11e8-9561-d3ea8048d502.jpg)
![original front](https://user-images.githubusercontent.com/20902507/36072540-1d64b618-0f5c-11e8-9e76-0c0343b171f2.jpg)
![variant1 front](https://user-images.githubusercontent.com/20902507/36072541-1dab4efc-0f5c-11e8-99bb-8f5cca734a5d.jpg)

**Comment by VK6TT** [comment]
Some boards pics






![w1209](https://user-images.githubusercontent.com/20902507/36072393-098ebdb6-0f5a-11e8-947c-2984f65668dd.png)

**Comment by VK6TT** [comment]
CC pics


![variant cc front](https://user-images.githubusercontent.com/20902507/36081566-7ca0e230-0fdb-11e8-8b77-638b882ceedb.jpg)
![variant cc rear](https://user-images.githubusercontent.com/20902507/36081567-7cebaffe-0fdb-11e8-90b1-90019bb124ee.jpg)

**Comment by VK6TT** [comment]
![w1209](https://user-images.githubusercontent.com/20902507/36082169-c83ffe14-0fe1-11e8-85e5-d7f32f0b44e0.jpg)

**Comment by TG9541** [comment]
![stm8s105k6](https://user-images.githubusercontent.com/5466977/40583328-c46b7942-618c-11e8-901e-fd78cdef7304.png)
![stm8l051f3p6](https://user-images.githubusercontent.com/5466977/40583331-cf2690ce-618c-11e8-9e95-fa4bc70df551.png)

**Comment by TG9541** [comment]
![stm8l051f3p6_](https://user-images.githubusercontent.com/5466977/40583353-3882aeb8-618d-11e8-9a08-f7d27950777d.png)

**Comment by TG9541** [comment]
![stm8l051f3p6_](https://user-images.githubusercontent.com/5466977/40583511-8462f470-6190-11e8-8674-84338a991f58.png)

**Comment by TG9541** [comment]
[USBaspUSBaspLoader.zip](https://github.com/TG9541/stm8ef/files/2751947/USBaspUSBaspLoader.zip)

**Comment by TG9541** [comment]
![C0135-900x600](https://user-images.githubusercontent.com/5466977/64918808-a8043580-d7a3-11e9-98df-884f30a0d0e1.jpg)

**Comment by TG9541** [comment]
![C0135_Text](https://user-images.githubusercontent.com/5466977/64919487-9f176200-d7ab-11e9-9a4f-00d0d6d24ceb.png)

**Comment by TG9541** [comment]
![test-clips](https://user-images.githubusercontent.com/5466977/64919964-f7e9f900-d7b1-11e9-9cd0-e2bb2fbb2d99.png)

**Comment by TG9541** [comment]
![test-clips-220](https://user-images.githubusercontent.com/5466977/64919984-48f9ed00-d7b2-11e9-97f9-51145d98a687.png)

**Comment by TG9541** [comment]
![soldering-iron-220](https://user-images.githubusercontent.com/5466977/64920134-eefa2700-d7b3-11e9-82e1-57d708614227.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/71879655-dd57d900-312e-11ea-8c40-7febebe59be3.png)

![image](https://user-images.githubusercontent.com/5466977/71879719-09735a00-312f-11ea-82ad-a0f8fdab2272.png)

**Comment by TG9541** [comment]
Pseudo-W1219
![image](https://user-images.githubusercontent.com/5466977/77845846-35dcc680-71b2-11ea-9078-d089ba790c9e.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/93012522-7f26a400-f5a1-11ea-808c-c56f83449bf3.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/96503648-e0eac580-1253-11eb-9f5f-7f3724e99d13.png)

**Comment by TG9541** [comment]
STM8S105x4/6 Pinout and pin description 

Figure 3. LQFP48 pinout
![image](https://user-images.githubusercontent.com/5466977/96959663-d4d76000-1500-11eb-9c29-4cb9a46d3e37.png)

Figure 4. LQFP44 pinout
![image](https://user-images.githubusercontent.com/5466977/96959547-99d52c80-1500-11eb-897f-18cc6b8f7877.png)

Figure 5. UFQFPN32/LQFP32 pinout
![image](https://user-images.githubusercontent.com/5466977/96959390-3945ef80-1500-11eb-8b82-3f9cfdfba66b.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/97478082-c1892200-1950-11eb-9e21-a3ae54c5ff5f.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/97488113-15e6ce80-195e-11eb-8e6a-88ebf5c2dd4e.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/97802410-71a5a600-1c43-11eb-9f34-a20eda68fdff.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/97846009-abcb8200-1ced-11eb-9771-d854373b7ec5.png)
![image](https://user-images.githubusercontent.com/5466977/97846163-e6cdb580-1ced-11eb-8da3-9708306d742a.png)

**Comment by TG9541** [comment]
[ Experiments with the STM8 I2C peripheral ](https://gist.github.com/TG9541/5c3405320794d91ef8129734a4bfc880)

![image](https://user-images.githubusercontent.com/5466977/99192783-190ef680-2775-11eb-9b07-ed783cb7903d.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/100022117-e901cc00-2de2-11eb-8933-0543541fe723.png)
There is obviously no way for resetting the TXE flag when there is no write to I2C_DR.

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/102696370-14cf7080-422e-11eb-89cb-ee54946c3d20.png)



![image](https://user-images.githubusercontent.com/5466977/102696284-81963b00-422d-11eb-9332-a2e0eb6aabf7.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/166191498-b5251266-0a66-448f-b1a1-d242d86aa54f.png)
![image](https://user-images.githubusercontent.com/5466977/166191585-cbfcc22c-c5ef-4b54-b756-c9185ff3957b.png)

**Comment by TG9541** [comment]
![stm8l101f3](https://user-images.githubusercontent.com/5466977/216818185-c99d6860-7e7e-4bf7-b640-86faa5106ca2.png)

**Comment by TG9541** [comment]
![image](https://user-images.githubusercontent.com/5466977/227766294-f8e4d8c7-b75e-44ee-b0b6-76f6dbc16561.png)
