### ISSUE TITLE
Calibration of Repaired ZB2L3 (HW-586 v3.0) Board

### ISSUE THREAD

**Issue by wolf-t-me** [TG9541/stm8ef#471]
I bought this board recently but he  micro USB port broke off after very limited use and I was unable to re-attach it.
I identified tat I could power the board by soldering a severed USB cable's  + and - wires directly to two exposed solder points on the rear of the board.
It works fine but it will not allow me to enter calibration mode, which would normally be achieved by pressing and holding the three micro-switches while powering up the board.
It would seem that the physical insertion of a micro USB male to the original port provides an additional trigger to initialise the calibration function.
Can anyone suggest a way of entering calibration while the unit is being powered in my unconventional way?

**Comment by TG9541** [comment]
So far the class of somewhat pin-compatible microcontrollers that power the ZB2L3 board, i.e., the STM8S003F3P6 or lookalikes with different architectures like MCS-51, RISC-V, or most exotic things, doesn't have a USB peripheral.

I guess that you'll need to look more carefully for some other electrical defect. If, however, you've reason to believe that there is a new type of microcontroller that does indeed have a USB peripheral, I'd be happy to learn about it!
