### ISSUE TITLE
TOS in low memory

### ISSUE THREAD

**Issue by larsbrinkhoff** [TG9541/stm8ef#53]
Hello,

Have you considered putting the top data stack element in low memory, where it can be accessed using short memory addressing mode?

**Comment by larsbrinkhoff** [comment]
Never mind.  I tried it, and it didn't seem to be a win.

**Comment by TG9541** [comment]
Hi Lars,
TOS in a "zero page" cell is an interesting idea, however most 16bit operations demand X or/and Y as an operant. Great that you already did a test implementation!

Using the return stack as data stack with (n,SP)-addressing looks interesting, but this requires a DTC or ITC implementation, and interrupt handlers in Forth would be a bit risky.

**Comment by larsbrinkhoff** [comment]
Right, I wanted to use SP-relative addressing many times.  The sdcc compiler use it to access parameters and local variables.  It's a shame a native-code Forth compiler can't.

**Comment by TG9541** [comment]
Do you know any source code of a DTC Forth kernel that used the native return stack as the data stack?

**Comment by larsbrinkhoff** [comment]
DTC, no.  ITC, yes.  Can't say I know many Forth implementations, though.
