### ISSUE TITLE
Compilation  fails

### ISSUE THREAD

**Issue by timsoer** [TG9541/stm8ef#59]
sdasstm8 -I. -I./MINDEV -plosgffw out/MINDEV/forth.rel forth.asm
forth.asm:1447: Error: <i> .include file error or an .if/.endif mismatch

**Comment by TG9541** [comment]
What was your command line?

**Comment by TG9541** [comment]
This was a `make BOARD=MINDEV flash` in  89ef113, right?

**Comment by TG9541** [comment]
OK, confirmed - thanks for reporting! 
A new release with some improvements was planned for today, it will also fix this bug. Please remove line 1446 for now!

**Comment by TG9541** [comment]
With bed2c73 @larsbrinkhoff fixed the root-cause of this issue once and for all: there is now a travis-ci continuous integration set-up. Thanks a lot!

**Comment by larsbrinkhoff** [comment]
That was the idea!  Happy to help.

**Comment by TG9541** [comment]
I just enabled "Branch protection for master". I would happily also apply the restrictions also to administrators provided the team is large enough (i.e. time to review is guaranteed). 
[![screenshot](https://screenshots.firefoxusercontent.com/images/d783ad63-0081-47e9-81d6-966ba7f02a6b.png)](https://screenshots.firefox.com/Y35e5QqYA1fG7tzm/github.com)

**Comment by larsbrinkhoff** [comment]
I think requiring status checks, e.g. passing builds on Travis CI, also makes sense.

**Comment by TG9541** [comment]
You're right about the status checks. I didn't realize that Travis-CI acts as a status-check service.

I made some progress with containerizing the tool chain but there's still a problem with a recent change in uCsim that stops the simulator after injecting UART code. Automated eForth core tests will be good to have.
