### ISSUE TITLE
HSI Calibration errors

### ISSUE THREAD

**Issue by barewires** [TG9541/stm8ef#64]
\ Trying to trim HSI I had a defective device with 3 identical lowest frequencies verified on scope. Now it works! Still a useful excercise.
\ eForth on STM8S103F3 running MINDEV
\ en.CD00208721.pdf
\  my contrib under user barewires
\ initTIM1 and content from previous page 1
\ (HCDVBD0034)
\ forum.hobbycomponents.com - View topic - STM8S103F3 Development Board 
\ 1st try trim freq and confirm register read-back at 16 kHz
\
FILE
NVM
: CLK_HSITRIMR $50CC ;
: f3 3 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 15.45 lowest freq 
: f2 2 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 15.52 
: f1 1 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 15.70
: f0 0 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 15.87 kHz reset value
: f7 7 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 16.05
: f6 6 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 16.24
: f5 5 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 16.43
: f4 4 CLK_HSITRIMR C! CLK_HSITRIMR C@ . ; \ 16.62 highest freq
RAM
HAND
initTIM1
16000 Hz
f3 3 ok

**Comment by TG9541** [comment]
Thanks, that's an instructive experiment. I'll leave it here for linking :-)
