### ISSUE TITLE
Minor version number

### ISSUE THREAD

**Issue by barewires** [TG9541/stm8ef#68]
May I suggest having the minor version number appended to the header:
stm8eForth v2.2.xx

**Comment by TG9541** [comment]
The revision number should indeed be visible (the 2nd group of digits is usually called the minor).  
But what should we do with development versions, and when should be increment the revision number?
Maybe we need to be more generous with the minor.
Any thoughts?

**Comment by barewires** [comment]
I suppose with all of the targets and devices that it could easily become unmanageable. Best if I put it in eeprom for my own records. Yes, a complex issue but worth thinking about. Thanks, no longer an issue.

**Comment by barewires** [comment]
Just blasted the latest version 2.2.16 and as a major release can you reconsider adding .16
/home/pi/Downloads/2216/out/MINDEV/MINDEV.ihx

hi
stm8eForth v2.2.16

**Comment by TG9541** [comment]
I'll be looking into how to pass the revision number, and the release status, into the build chain.

**Comment by TG9541** [comment]
This issue will be resolved in #67: the revision number will be generated from a "package.json" file
